//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heatpump_Control.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Heatpump_Control.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEATPUMPREMOTE.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response.
        /// </summary>
        public static string CommandNoResponse {
            get {
                return ResourceManager.GetString("CommandNoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command sent.
        /// </summary>
        public static string CommandSent {
            get {
                return ResourceManager.GetString("CommandSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are connected to WiFi with SSID.
        /// </summary>
        public static string ConnectedToSSID {
            get {
                return ResourceManager.GetString("ConnectedToSSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connection settings.
        /// </summary>
        public static string ConnectionSettings {
            get {
                return ResourceManager.GetString("ConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No controllers found.
        /// </summary>
        public static string ControllersNotFound {
            get {
                return ResourceManager.GetString("ControllersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heatpump name must be defined.
        /// </summary>
        public static string EmptyHeatpumpName {
            get {
                return ResourceManager.GetString("EmptyHeatpumpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAN SPEED.
        /// </summary>
        public static string FanSpeed {
            get {
                return ResourceManager.GetString("FanSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller ID.
        /// </summary>
        public static string HeatpumpControllerID {
            get {
                return ResourceManager.GetString("HeatpumpControllerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to controllers.
        /// </summary>
        public static string HeatpumpControllers {
            get {
                return ResourceManager.GetString("HeatpumpControllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heatpump model.
        /// </summary>
        public static string HeatpumpModel {
            get {
                return ResourceManager.GetString("HeatpumpModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heatpump name.
        /// </summary>
        public static string HeatpumpName {
            get {
                return ResourceManager.GetString("HeatpumpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heatpumps.
        /// </summary>
        public static string Heatpumps {
            get {
                return ResourceManager.GetString("Heatpumps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send.
        /// </summary>
        public static string IRSend {
            get {
                return ResourceManager.GetString("IRSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heatpump type must be selected.
        /// </summary>
        public static string MustSelectType {
            get {
                return ResourceManager.GetString("MustSelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No heatpumps configured, and not connected to WiFi.
        /// </summary>
        public static string NoHeatpumpsAndWiFi {
            get {
                return ResourceManager.GetString("NoHeatpumpsAndWiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No WiFi.
        /// </summary>
        public static string NoWiFi {
            get {
                return ResourceManager.GetString("NoWiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPERATINGMODE.
        /// </summary>
        public static string OperatingMode {
            get {
                return ResourceManager.GetString("OperatingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string PowerStateOFF {
            get {
                return ResourceManager.GetString("PowerStateOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string PowerStateON {
            get {
                return ResourceManager.GetString("PowerStateON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchControllers {
            get {
                return ResourceManager.GetString("SearchControllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for heatpump controllers?.
        /// </summary>
        public static string SearchForControllers {
            get {
                return ResourceManager.GetString("SearchForControllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending command....
        /// </summary>
        public static string SendingCommand {
            get {
                return ResourceManager.GetString("SendingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved.
        /// </summary>
        public static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restored default settings.
        /// </summary>
        public static string SettingsWiped {
            get {
                return ResourceManager.GetString("SettingsWiped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH account.
        /// </summary>
        public static string SSHAccount {
            get {
                return ResourceManager.GetString("SSHAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH key.
        /// </summary>
        public static string SSHKey {
            get {
                return ResourceManager.GetString("SSHKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH password.
        /// </summary>
        public static string SSHPassword {
            get {
                return ResourceManager.GetString("SSHPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH server port.
        /// </summary>
        public static string SSHPort {
            get {
                return ResourceManager.GetString("SSHPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH server.
        /// </summary>
        public static string SSHServer {
            get {
                return ResourceManager.GetString("SSHServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use key.
        /// </summary>
        public static string SSHUseKey {
            get {
                return ResourceManager.GetString("SSHUseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use password.
        /// </summary>
        public static string SSHUsePassword {
            get {
                return ResourceManager.GetString("SSHUsePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Wifi SSID.
        /// </summary>
        public static string SSIDSetting {
            get {
                return ResourceManager.GetString("SSIDSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMPERATURE.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDP broadcast command.
        /// </summary>
        public static string UDPBroadcastSetting {
            get {
                return ResourceManager.GetString("UDPBroadcastSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restore default settings.
        /// </summary>
        public static string WipeSettings {
            get {
                return ResourceManager.GetString("WipeSettings", resourceCulture);
            }
        }
    }
}
